site:
  title: Apache Camel

content:
  sources:
    - url: ../
      branches: master
      start_path: docs/user-manual
    - url: ../
      branches: master, HEAD
      start_path: docs/components

ui:
  bundle:
    url: not-used
